### ISSUE TITLE
Mary Geschwindt Assignment 1 Complete

### ISSUE THREAD

**Issue by marygeschwindt** [SES-5215-F2020/mgeschwindt-quant#1]
I have completed Assignment 1. The HTML can be viewed at this link: https://ses-5215-f2020.github.io/mgeschwindt-quant/Assignment1_Final

@c-voulgaris 
@saratepfer

**Comment by saratepfer** [comment]
Great job! Nice use of PUMAs to filter the population. I think it may be interesting to keep the PUMA data in your dataset/export, along with the other variables, in case you are interested in looking for relationships between location and the other variables.
