### ISSUE TITLE
Assignment 2 is Ready for Grading

### ISSUE THREAD

**Issue by marygeschwindt** [SES-5215-F2020/mgeschwindt-quant#2]
My completed assignment 2 is submitted for grading.

Link to my completed Assignment 2: https://ses-5215-f2020.github.io/mgeschwindt-quant/Assignment2

I want to note 2 issues that I am aware of with this submission:
1. I am aware that there is a graphic issue with line breaks of long strings of code in which a string of code will jump to the next line and not be indented properly - I have been working on resolving this issue and hope to know how to properly resolve this by the time I complete my next assignment. This is something that only occurs when I knit the document.
2. I am still having issues pushing to GitHub from RStudio. I get an error when attempting to commit that my Assignment 2 files are not in my remote folder (even though I can see them there). I think I am just not aware of how to use the Pull function. Therefore I used the "upload" function on GitHub for this assignment, and hope to have learned how to resolve this for Assignment 3.

@c-voulgaris 
@saratepfer

**Comment by saratepfer** [comment]
Thank you, Mary! Nice job on this. For the problems that you noted when you opened the issue, please feel free to drop by office hours or schedule an appointment with me or Carole to troubleshoot. Please also see a few comments below:

**Comments on Code**
- Lines 65, 188, 253, 293: results='hide' here means that the tables you're creating with knittr::kable aren't displayed.

**Comments on Content**
- General comment on interpretations: be careful when using the word "significant", as it has special meaning in statistics (as we've seen with p-value interpretations). I wouldn't call outliers significant (perhaps "strong" instead?) 
- Your histogram interpretations are very thorough, so good job! But try also to be a bit more specific with some of your words. For example, what do you mean by "regular"?
