### ISSUE TITLE
Assignment 3 is Ready for Grading

### ISSUE THREAD

**Issue by marygeschwindt** [SES-5215-F2020/mgeschwindt-quant#3]
Hello,

My quant assignment 3 is now ready for grading. Please find my submission at this link: https://ses-5215-f2020.github.io/mgeschwindt-quant/Assignment3.html

Thanks!

@c-voulgaris 
@saratepfer

**Comment by saratepfer** [comment]
Nice job on this, Mary! I think a big takeaway I had from your assignment is setting straight the difference between correlation and significance. The p-value is an indicator of statistical significance, not the strength or direction of the relationship. Please feel free to come to office hours if you would like further clarification. For now, please see a few comments below:

- line 93: I believe you are referring to the correlation value, which is an indicator of strength/weakness, not the p-value here. p-value gives an indication of significance, which should also be included in the interpretation.
- line 118: Similarly as above, I believe you are getting p-value and correlation value confused. If the p-value is about 0.86, then p > .05, and the relationship is not significant. You reach the same conclusion using the confidence interval, but it would be good to get this confusion straightened out.
- line 137: be careful about the location of your annotation. unfortunately it is running off the plot and is difficult to read.
- line 152: p value is greater than .05, therefore there is no significant relationship at a 95% confidence interval.
- line 185: same as above.
- if you would like to remove scientific notation from your plot, insert the following code above the ggplot() call: options(scipen = 999).
- Be sure to also take significance into account (p-value) when interpreting the Tukey HSD tests. Also, it's not quite that it's a positive or negative correlation, rather it's the observed difference in the pairs compared for each row of the Tukey test. I'm sorry if I'm not giving a very complete answer here. Please feel free to come to office hours to clarify the Tukey test interpretation.
