### ISSUE TITLE
Assignment 4 Is Ready for Grading

### ISSUE THREAD

**Issue by marygeschwindt** [SES-5215-F2020/mgeschwindt-quant#4]
My Assignment 4: Linear Regression Model is ready for grading. Please follow this link to my completed assignment: https://ses-5215-f2020.github.io/mgeschwindt-quant/Assignment4.html

Thank you!

@c-voulgaris 
@saratepfer

**Comment by saratepfer** [comment]
Nice job on this, Mary! Your interpretations and code look good to me.
