### ISSUE TITLE
Assignment 5 Issue - Not a Submission

### ISSUE THREAD

**Issue by marygeschwindt** [SES-5215-F2020/mgeschwindt-quant#5]
I'm able to run through the entirety of Assignment 5 until I get to the code for comparing all of the models I've created. The error I get says:

"Error in (function (..., error_format = "({std.error})", error_pos = c("below", : Unrecognized coefficient names: JWTR_label, DPHY_label, DPHY_label:AGEP, JWTR_label:AGEP"

Please note that I canceled the code using # so that I could knit the document.

My HTML can be found at this link: https://ses-5215-f2020.github.io/mgeschwindt-quant/Assignment-5.html 

Thank you!

@saratepfer 
@c-voulgaris

**Comment by saratepfer** [comment]
Hi Mary,

I believe it has to do with how you've assigned your coefficient names. They need to match the model names in your regression model. I believe the following replacement for coeff_names should work: 
coeff_names <- c("Means of Transportation\nto work(compared to car" = "JWTR_labelBicycle",
                 "Income (dollars)" = "PINCP",
                 "Income\n(log-transformed)" = "log(PINCP)",
                 "Age (years)" = "AGEP",
                 "Physical Disability\n(compared to not disabled)" = "DPHY_labelPhysically Disabled",
                 "Interaction: Disability and Age" = "DPHY_labelPhysically Disabled:AGEP",
                 "Interaction: Means of Transportation\nto Work and Age" = "JWTR_labelBicycle:AGEP")

please let me know if it continues to not work. Thank you.

**Comment by marygeschwindt** [comment]
Hi Sara,

This worked perfectly, thank you!
