### ISSUE TITLE
Assignment 5 Is Ready for Grading

### ISSUE THREAD

**Issue by marygeschwindt** [SES-5215-F2020/mgeschwindt-quant#6]
Hello,

My Assignment 5 submission is now ready for grading. Please follow this link to my assignment: https://ses-5215-f2020.github.io/mgeschwindt-quant/Assignment-5_Final

Thank you!

@saratepfer 
@c-voulgaris

**Comment by c-voulgaris** [comment]
Good job! I'm looking forward to reviewing your final project.
